const VERSION='0.3.0.0';
const KEY='gheaTactico0300';
const app=document.querySelector('#app');
const $=s=>document.querySelector(s);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const badWords=['puta','puto','mierda','pelotudo','pelotuda','boludo','boluda','concha','verga','pija','coger'];
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{characters:[],selected:null};
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function hero(){return state.characters[state.selected]}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function validName(n){let x=n.trim().toLowerCase();return n.trim().length>=1&&n.trim().length<=16&&!badWords.some(w=>x.includes(w))}
function baseChar(name,race='Humano',cls='Guerrero'){return {id:crypto.randomUUID?.()||String(Date.now()),name:name.trim(),race,cls,level:1,xp:0,xpNext:2,hp:12,baseHp:10,equipment:{armor:'Ropa común',boots:'Botas comunes',weapon:null},pa:4,pm:3,quest:'hablar-maestro',tutorial:0,pos:{x:50,y:58},dev:0,tree:{power:0,block:0}}}
function shell(inner){app.innerHTML=`<main class="proto">${inner}</main>`}
function title(){shell(`<section class="title-screen"><div><h1>GHEA TÁCTICO</h1><p>v${VERSION} · Reestructuración funcional</p><button id="start">INICIAR</button></div></section>`);$('#start').onclick=menu}
function menu(){shell(`<section class="menu-screen"><h2>Ghea Táctico</h2><button id="new">Nueva partida</button><button id="cont">Continuar partida</button><button id="opt" class="secondary">Opciones</button><button id="exit" class="secondary">Salir</button><p class="muted">${state.characters.length}/3 aventureros creados</p></section>`);$('#new').onclick=create;$('#cont').onclick=continueGame;$('#opt').onclick=()=>alert('Opciones se desarrollará más adelante.');$('#exit').onclick=()=>alert('En la versión web/PWA el sistema no permite cerrar la app directamente.')}
function create(){if(state.characters.length>=3)return alert('Máximo de 3 aventureros.');shell(`<section class="form-screen"><h2>Nuevo aventurero</h2><label>Nombre <input id="name" maxlength="16" placeholder="Máximo 16 caracteres"></label><label>Raza <select id="race"><option>Humano</option><option disabled>Enano — próximamente</option><option disabled>Elfo — próximamente</option></select></label><label>Clase <select id="cls"><option>Guerrero</option><option disabled>Más clases — próximamente</option></select></label><p id="err" class="error"></p><div class="row"><button id="back" class="secondary">Volver</button><button id="ok">Confirmar</button></div></section>`);$('#back').onclick=menu;$('#ok').onclick=()=>{let n=$('#name').value;if(!validName(n)){ $('#err').textContent='Nombre no válido. Usá 1–16 caracteres y evitá palabras ofensivas.';return}let c=baseChar(n,$('#race').value,$('#cls').value);state.characters.push(c);state.selected=state.characters.length-1;save();arca()}}
function continueGame(){shell(`<section class="select-screen"><h2>Continuar partida</h2><div class="cards">${state.characters.length?state.characters.map((c,i)=>`<button class="char-card ${state.selected===i?'selected':''}" data-i="${i}"><img src="assets/guerrero-ficha.png"><span><b>${esc(c.name)}</b><small>${c.race} · ${c.cls} · Nivel ${c.level}</small><small>❤️ ${c.hp} · EXP ${c.xp}/${c.xpNext}</small></span></button>`).join(''):'<p>No hay aventureros creados.</p>'}</div><div class="row"><button id="back" class="secondary">Volver</button><button id="ok" ${state.characters.length?'':'disabled'}>Confirmar</button></div></section>`);document.querySelectorAll('.char-card').forEach(b=>b.onclick=()=>{state.selected=+b.dataset.i;continueGame()});$('#back').onclick=menu;if($('#ok'))$('#ok').onclick=()=>{save();arca()}}
const blockers=[{x:5,y:6,w:28,h:18,label:'Mercado'},{x:67,y:6,w:28,h:18,label:'Academia'},{x:6,y:72,w:25,h:20,label:'Herrería'},{x:69,y:72,w:25,h:20,label:'Tienda'}];
const teacher={x:80,y:34}; const dummy={x:77,y:50};
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
function blocked(x,y){return blockers.some(b=>x>b.x-2&&x<b.x+b.w+2&&y>b.y-2&&y<b.y+b.h+2)}
function objective(c){if(c.tutorial===0)return 'Hablá con el Maestro de la Academia';if(c.tutorial===1)return 'Acercate al Muñeco de Paja';if(c.tutorial===2)return 'Derrotá al Muñeco de Paja';return 'Tutorial inicial completado'}
function arca(){let c=hero();if(!c)return menu();shell(`<section class="game"><header><button id="menu" class="tiny">☰</button><div><b>${esc(c.name)}</b><small>Nivel ${c.level} · ❤️ ${c.hp} · EXP ${c.xp}/${c.xpNext}</small></div></header><div class="objective">📜 ${objective(c)}</div><div id="map" class="arca-map"><div class="plaza">PLAZA CENTRAL<div class="monument">◆<small>Monumento</small></div></div>${blockers.map(b=>`<div class="block" style="left:${b.x}%;top:${b.y}%;width:${b.w}%;height:${b.h}%">${b.label}</div>`).join('')}<div class="road north"></div><div class="road eastwest"></div><div class="npc teacher" style="left:${teacher.x}%;top:${teacher.y}%">M<small>Maestro</small></div><div class="npc dummy" style="left:${dummy.x}%;top:${dummy.y}%">✚<small>Muñeco</small></div><img id="hero" class="hero-token" src="assets/guerrero-ficha.png" style="left:${c.pos.x}%;top:${c.pos.y}%"><div id="context" class="context"></div></div><p class="hint">Tocá una zona libre para desplazarte. Escala de prueba: Arca ~100×100 m.</p></section>`);$('#menu').onclick=menu;let map=$('#map'),token=$('#hero');function context(){let html='';if(c.tutorial===0&&dist(c.pos,teacher)<11)html='<button id="talk">Hablar con Maestro</button>';if(c.tutorial===1&&dist(c.pos,dummy)<10)html='<button id="fight">Seleccionar Muñeco</button>';$('#context').innerHTML=html;if($('#talk'))$('#talk').onclick=teacherTalk;if($('#fight'))$('#fight').onclick=()=>{c.tutorial=2;save();battle()}}function moveTo(x,y){if(blocked(x,y))return; c.pos={x:clamp(x,3,97),y:clamp(y,4,96)};token.style.left=c.pos.x+'%';token.style.top=c.pos.y+'%';save();context()}map.onclick=e=>{if(e.target.closest('button'))return;let r=map.getBoundingClientRect();moveTo((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100)};context()}
function teacherTalk(){let c=hero();document.body.insertAdjacentHTML('beforeend',`<div class="modal2" id="modal"><div><h3>Maestro</h3><p>Bienvenido, ${esc(c.name)}. Antes de comenzar tu aventura tendrás que superar una última prueba.</p><p>Tomá esta <b>Espada de madera</b>. Quiero que te enfrentes al Muñeco de Paja.</p><button id="accept">Aceptar prueba</button></div></div>`);$('#accept').onclick=()=>{c.equipment.weapon='Espada de madera';c.tutorial=1;save();$('#modal').remove();arca()}}
function battle(){let c=hero();let b={heroHp:c.hp,dummyHp:4,pa:4,pm:3,attacks:0,turn:'hero',round:1};function draw(){shell(`<section class="battle-proto"><header><b>Prueba 1 · Fundamentos</b><span>Turno ${b.round}</span></header><div class="battle-info"><span>❤️ ${b.heroHp}</span><span>PA ${b.pa}/4</span><span>PM ${b.pm}/3</span><span>Muñeco ❤️ ${b.dummyHp}/4</span></div><div class="grid10">${Array.from({length:100},(_,i)=>{let x=i%10,y=Math.floor(i/10);let content=(x===2&&y===7)?`<img src="assets/guerrero-ficha.png">`:(x===7&&y===3&&b.dummyHp>0)?'<div class="dummy-piece">✚</div>':'';return `<div class="cell">${content}</div>`}).join('')}</div><div class="tutorial-box">${b.turn==='hero'?'Tu turno. Ataque Normal cuesta 1 PA y tiene máximo 2 usos por turno.':'Turno del Muñeco.'}</div><div class="combat-actions"><button id="move">Mover</button><button id="attack" ${b.turn!=='hero'||b.pa<1||b.attacks>=2?'disabled':''}>Ataque normal</button><button id="end">Fin turno</button></div><button id="leave" class="secondary">Salir de prueba</button></section>`);$('#leave').onclick=arca;$('#move').onclick=()=>alert('Movimiento táctico: en la siguiente iteración activaremos selección de casillas.');$('#attack').onclick=()=>{b.pa--;b.attacks++;b.dummyHp=Math.max(0,b.dummyHp-1);if(b.dummyHp===0)return win();draw()};$('#end').onclick=()=>{b.turn='dummy';draw();setTimeout(()=>{b.heroHp=Math.max(1,b.heroHp-1);b.turn='hero';b.round++;b.pa=4;b.pm=3;b.attacks=0;draw()},450)}}function win(){c.hp=b.heroHp;c.xp+=1;c.tutorial=3;if(c.xp>=c.xpNext){c.xp-=c.xpNext;c.level++;c.xpNext=5;c.dev++}save();shell(`<section class="result"><h2>Victoria</h2><p>Muñeco de Paja derrotado.</p><p><b>+1 EXP</b></p><button id="return">Volver a Arca</button></section>`);$('#return').onclick=arca}draw()}
title();
